
# Docker Compose file for setting up a MariaDB service
# This file defines the service, its image, environment variables, volumes, and networks.
# une image Docker est un modèle pour créer des conteneurs, 
#tandis qu'un conteneur est une instance d'une image en cours d'exécution.
# Le fichier de configuration est écrit en YAML, un format lisible par l'homme pour
#décrire les services, les volumes et les réseaux nécessaires à l'application.

version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file: .env
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress_image
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
    networks:
      - inception_network

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: on-failure
    env_file: .env
    ports:
      - "10443:443"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_network

volumes:
  mariadb_data:
    driver: local
  wordpress:
    driver: local

networks:
  inception_network:
    driver: bridge
