
FROM debian:bullseye

RUN apt update && apt install -y nginx
RUN apt install openssl -y
RUN apt install curl -y

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 365 \
  -newkey rsa:2048 \
  -keyout /etc/nginx/ssl/inception.key \
  -out /etc/nginx/ssl/inception.crt \
  -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=jelecoq.42.fr/UID=jelecoq"

RUN mkdir -p /var/run/nginx

RUN rm -f /etc/nginx/conf.d/*
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/wordpress.conf /etc/nginx/conf.d/default.conf

RUN chmod 755 /var/www/html \
    && chown -R www-data:www-data /var/www/html

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
